### ISSUE TITLE
name of the snapshot not showing in aws.

### ISSUE THREAD

**Issue by gabrielpvbw** [backube/snapscheduler#282]
The name of the snapshot is not showing in aws. I am not sure if it's suppose to be like that, but I would like to have the actual snapshot name in aws as well.

Right now it only has a dash there

<img width="678" alt="image" src="https://user-images.githubusercontent.com/100797215/202533119-611002a6-da10-4895-877f-a30e6d987460.png">

**Comment by JohnStrunk** [comment]
It sounds like you're getting snapshots as expected, they just aren't named how you would prefer...

The CSI driver is ultimately responsible for creating the snapshot on the back end storage. In your case, I'm guessing this would be the EBS CSI driver: https://github.com/kubernetes-sigs/aws-ebs-csi-driver

Assuming the EBS driver supports what you are trying to do, if some sort of kube-level annotation or label is necessary w/in SnapScheduler, feel free to open an enhancement request.
