### ISSUE TITLE
Latest helm chart is required

### ISSUE THREAD

**Issue by Pavaningithub** [backube/snapscheduler#458]
**Describe the bug**

In `master` branch, under helm/charts  > values.yaml, `podAnnotations` parameter is available. But the same is not available in the latest helm chart. The last release was made in October 2022. When are you planning to create a new release?

**Steps to reproduce**

deploying using two different methods.

**Expected behavior**

latest helm chart release should have all the options available.

**Actual results**

`podAnnotations` and another parameters of the helm chart is not available for the end user.

**Additional context**

**Comment by JohnStrunk** [comment]
released v3.3.0 today
